# .github/workflows/deploy.yml

name: deploy
on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    env:
      AMPT_API_KEY: ${{ secrets.AMPT_API_KEY }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v1
        with:
          node-version: 18
      - run: npm ci
      - run: npx @ampt/cli deploy prod
